Draft PR
tin0312/walk-more-than-you-scroll pull request #5
Opened 2023-08-01 17:03 UTC by tin0312

fixes #1

2023-08-09 02:43 UTC, tin0312 commented
fixed #1

2023-08-09 02:45 UTC, DukeManh requested changes

2023-08-09 02:45 UTC, DukeManh commented on content.css
> +.fps-counter {
```suggestion
.scroll-counter {
```

2023-08-09 02:45 UTC, DukeManh commented on content.js
> +  div.innerHTML = `Scroll Distance : ${distanceCM} cm `;
```suggestion
  `${distanceCM} cm `;
```

2023-08-09 02:48 UTC, DukeManh reviewed
It's very close

2023-08-09 02:49 UTC, DukeManh commented on content.css
> +    align-items: center;
Add `z-index` here to make sure the counter is always visible

2023-08-10 04:19 UTC, DukeManh approved these changes

2023-08-10 04:21 UTC, merged