Use m instead of cm
tin0312/walk-more-than-you-scroll pull request #9
Opened 2023-08-12 19:09 UTC by tin0312

fixes #8

2023-08-16 03:12 UTC, tin0312 commented
fixes #6

2023-08-16 15:49 UTC, DukeManh requested changes

2023-08-16 15:49 UTC, DukeManh commented on utils.js
> +// Reusable logic
Suggestion: remove this comment

2023-08-16 15:49 UTC, DukeManh commented on utils.js
> +    }
Please format the file manually, we will setup linter later.

2023-08-16 15:49 UTC, DukeManh commented on feed.html
U can this file for the commit

2023-08-16 15:50 UTC, DukeManh commented
Can you squash the commits to one as well?

2023-08-17 03:58 UTC, tin0312 commented
fixed #9

2023-08-17 16:09 UTC, DukeManh approved these changes

2023-08-17 18:49 UTC, merged